#---------------------------------#
#      general configuration      #
#---------------------------------#

# branches to build
#branches:
#  # whitelist
#  only:
#    - master

# Start builds on tags only
#skip_non_tags: true

# Build worker image (VM template)
image: Visual Studio 2017

#---------------------------------#
#       build configuration       #
#---------------------------------#

version: '{build}'

environment:
  QT_Ver: 5.12
  Icestorm_Release: https://github.com/FPGAwars/toolchain-icestorm/releases/download/v1.11.1/toolchain-icestorm-windows_x86-1.11.1.tar.gz
  FPGA_Arch: ice40
  
# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: x86

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

build:
  parallel: true                  # enable MSBuild parallel builds

  # MSBuild verbosity level
  verbosity: detailed

install:
  # MSVC Paths
  # https://www.appveyor.com/docs/lang/cpp/#visual-studio
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"

  # QT Paths
  # https://www.appveyor.com/docs/build-environment/#qt
  - set QTDIR=C:\Qt\%QT_Ver%\msvc2017
  - set PATH=%PATH%;%QTDIR%\bin
  # Setup cmake for Qt
  - set Qt5_Dir=C:\Qt\%QT_Ver%\msvc2017\lib\cmake
  
  # Boost Libs
  - set BOOST_ROOT=C:\Libraries\boost_1_69_0

  # Python
  - set PATH=%PATH%;C:\Python36

  # Icestorm tools
  - ps:Start-FileDownload %Icestorm_Release% -FileName icestorm.tar.gz
  - 7z x icestorm.tar.gz -oC:\projects\icestorm
  - set ICESTORM=C:\projects\icestorm

  # Required packages
  - vcpkg install eigen3
  - set Eigen3_DIR=C:\tools\vcpkg\installed\x86-windows\share\eigen3
  
build_script:
  - cmake -DARCH=%FPGA_Arch% -G "Visual Studio 15 2017" -DICEBOX_ROOT=%ICESTORM%\share\icebox .
  - msbuild /p:Configuration=Release /p:Platform=Win32 nextpnr.sln
artifacts:
  - path: install\win\*.exe
  - path: app\*.pdb

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
