#---------------------------------#
#      general configuration      #
#---------------------------------#

# branches to build
#branches:
#  # whitelist
#  only:
#    - master

# Start builds on tags only
#skip_non_tags: true

# Build worker image (VM template)
image: Visual Studio 2017

#---------------------------------#
#       build configuration       #
#---------------------------------#

version: '{build}'

environment:
  QT_Ver: 5.12
  
# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: x86

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

build:
  parallel: true                  # enable MSBuild parallel builds

  # MSBuild verbosity level
  verbosity: detailed

install:
  # MSVC Paths
  # https://www.appveyor.com/docs/lang/cpp/#visual-studio
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"

  # QT Paths
  # https://www.appveyor.com/docs/build-environment/#qt
  - set QTDIR=C:\Qt\%QT_Ver%\msvc2017
  - set PATH=%PATH%;%QTDIR%\bin

  # Required packages
  - vcpkg install boost-filesystem boost-program-options boost-thread boost-python qt5-base eigen3
  

build_script:
  - cmake -DARCH=ice40 -DICEBOX_ROOT=C:/ProgramData/icestorm/share/icebox -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x86-windows -G "Visual Studio 15 2017" -DPYTHON_EXECUTABLE=C:/Python364/python.exe -DPYTHON_LIBRARY=C:/vcpkg/packages/python3_x64-windows/lib/python36.lib -DPYTHON_INCLUDE_DIR=C:/vcpkg/packages/python3_x64-windows/include/python3.6
  - cmake --build . --config Release

artifacts:
  - path: install\win\*.exe
  - path: app\*.pdb